### ISSUE TITLE
DecimalScaleNormalizer output problem

### ISSUE THREAD

**Issue by yolile** [neuroph/neuroph#30]
I'm using the **DecimalScaleNormalizer** class for normalize my dataset, the inputs are normalize correctly but the output not. 
Debbuging the normalize method I see that the class finds the correct maxOut value but in the method **findScaleVectors()**:
```
  this.scaleFactorOut = new double[this.maxOut.length];

        for(i = 0; i < this.scaleFactorOut.length; ++i) {
            this.scaleFactorOut[i] = 1.0D;
        }

        for(i = 0; i < this.maxOut.length; ++i) {
            while(this.maxIn[i] > 1.0D) {
                this.maxOut[i] /= 10.0D;
                this.scaleFactorOut[i] *= 10.0D;
            }
        }
```

the value this.scaleFactorOut is 0 and then the scaleFactorOut is 1 and not 10.000 how is expect
The problem is the **while**, cause it's asking for the **maxIn** vector instead of **maxOut** vector

**Comment by bernard01** [comment]
In version 2.8.2, DecimalScaleNormalizer#findScaleVectors() code should not cause the issue as descibed above:

```
        for (int i = 0; i < maxOut.length; i++) {
            while (maxOut[i] > 1) {
                maxOut[i] = maxOut[i] / 10.0;
                scaleFactorOut[i] = scaleFactorOut[i] * 10;
            }
        }
```
		
So this issue can perhaps be closed.

**Comment by yolile** [comment]
Yes, you're right, apparently I have a previus version where this issue is present, but no more in this version
