### ISSUE TITLE
org.neuroph.nnet.learning.PerceptronLearning updates threshold wrongly

### ISSUE THREAD

**Issue by kaiyuanw** [neuroph/neuroph#48]
The current implementation does not converge when training logic OR function with perceptron learning.  Below is the reason I found.

The reason to update threshold is to avoid having a bias neuron according to http://stackoverflow.com/questions/6554792/whats-the-point-of-the-threshold-in-a-perceptron

> x1.w1 + x2.w2 = threshold

to

> x1.w1 + x2.w2 - 1.threshold = 0

where bias is -threshold.  So the way to update threshold should be
`threshold = threshold + this.learningRate * neuronError;`

See https://github.com/neuroph/neuroph/blob/master/neuroph-2.9/Core/src/main/java/org/neuroph/nnet/learning/PerceptronLearning.java#L63

**Comment by neuroph** [comment]
Thanks its fixed in the latest release
