### ISSUE TITLE
Master branch should be compiled with jdk1.8

### ISSUE THREAD

**Issue by cinqs** [neuroph/neuroph#50]
The `NeuralNetworkEventListener` interface of `org.neuroph.core.events` package used `FunctionalInterface` annotation, which is included in *jdk1.8*. So the project should be compiled with *jdk1.8*.

But inside *POM* file, which was indicated that

```xml
<maven.compiler.source>1.7</maven.compiler.source>
<maven.compiler.target>1.7</maven.compiler.target>
```

this should be solved, and I suggest that, don't use `FunctionalInterface` to keep compatible with *jdk1.7*

**Comment by cinqs** [comment]
checked with version 2.92 which was released on maven central repo. it was compiled with *jdk1.7*. So in my opinion, if the compiled jdk was changed, there should be a major release version like, *version 3.0* but not *2.93*.

**Comment by sevarac** [comment]
good point will change it

**Comment by cinqs** [comment]
Seems it already been changed, so issue will be closed
